export const COUNTER_CHANGE = 'COUNTER_CHANGE';

export const SAVE_FORM = 'SAVE_FORM';
export const RESET_FORM = 'RESET_FORM';
export const UPDATE_RESET_STATUS = 'UPDATE_RESET_STATUS';
export const UPDATE_FORM_STATUS = 'UPDATE_FORM_STATUS';